import torch
import numpy as np
from PIL import Image
import io
import time
import requests
import os

class SaveToPhoneTelegram:
    def __init__(self):
        self.output_dir = "temp"

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "images": ("IMAGE",),
                "bot_token": ("STRING", {"default": "YOUR_BOT_TOKEN_HERE"}),
                "chat_id": ("STRING", {"default": "YOUR_CHAT_ID_HERE"}),
                "caption": ("STRING", {"default": "Generated by ComfyUI"}),
            },
        }

    RETURN_TYPES = ()
    FUNCTION = "send_to_phone"
    OUTPUT_NODE = True
    CATEGORY = "Image/Postprocessing"

    def send_to_phone(self, images, bot_token, chat_id, caption):
        results = []
        
        for image in images:
            # Convert ComfyUI internal tensor format to a standard PIL Image
            i = 255. * image.cpu().numpy()
            img = Image.fromarray(np.uint8(i))
            
            # Save the image to a temporary memory buffer (no disk writing needed)
            bio = io.BytesIO()
            img.save(bio, format="PNG")
            bio.seek(0)
            
            # Construct the Telegram Bot API request
            url = f"https://api.telegram.org/bot{bot_token}/sendPhoto"
            files = {'photo': ('image.png', bio, 'image/png')}
            data = {'chat_id': chat_id, 'caption': caption}
            
            # Attempt to upload to your phone (retry once on rate limit)
            try:
                response = requests.post(url, data=data, files=files, timeout=120)
                if response.status_code == 429:
                    retry_after = response.json().get("parameters", {}).get("retry_after", 3)
                    time.sleep(retry_after + 1)
                    response = requests.post(url, data=data, files=files, timeout=120)
                if response.status_code == 200:
                    print(f"Successfully sent to phone!")
                else:
                    print(f"Failed to send: {response.text}")
            except Exception as e:
                print(f"Error sending to Telegram: {e}")
            time.sleep(0.8)  # keep below Telegram's per-chat rate limits

        # Standard ComfyUI return format
        return {"ui": {"images": results}}

# Registration for ComfyUI to recognize and map the node
NODE_CLASS_MAPPINGS = {
    "SaveToPhoneTelegram": SaveToPhoneTelegram
}

# The name that appears in the ComfyUI right-click "Add Node" menu
NODE_DISPLAY_NAME_MAPPINGS = {
    "SaveToPhoneTelegram": "📲 Save to Phone (Telegram)"
}